# Generated by Django 6.0.3 on 2026-03-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Eng_User', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('monthly_cost', models.FloatField()),
                ('cpu_utilization', models.FloatField()),
                ('is_unused', models.BooleanField(default=False)),
                ('current_size', models.CharField(max_length=50)),
                ('recommended_size', models.CharField(max_length=50)),
                ('carbon_waste_kg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_time', models.CharField(default='06:00', max_length=5)),
                ('end_time', models.CharField(default='20:00', max_length=5)),
            ],
        ),
    ]
