# Generated by Django 6.0.3 on 2026-03-08 22:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(verbose_name=django.contrib.auth.models.User),
        ),
    ]
